name: Agung Tedja
description: Freedom. Liberty. Independence.
meta_description: "Agung Hariadi Tedja's Personal Site"

aboutPage: false

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://tedja.me'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'zhenqianz'

# Details for the RSS feed generator
url:            'http://tedja.me'
author:         'Agung Tedja'
authorTwitter:  'agung_tedja'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
